config/routes.rb
Rails.application.routes.draw do
  # get 'lists', to: 'lists#index'
  # get 'lists/new', to: 'lists#new'
  # post 'lists', to: 'lists#create'
  # get 'lists/:id', to: 'lists#show'

  # get 'bookmarks/new', to: 'bookmarks#new'
  # post 'bookmarks', to: 'bookmarks#create'
  # delete 'bookmarks/:id', to: 'bookmarks#destroy'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  resources :lists, only: %i[index new create show] do
    resources :bookmarks, only: %i[new create destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :movie, presence: true
  validates :list, presence: true
  validates :comment, length: { minimum: 6 }
  belongs_to :movie
  belongs_to :list
  validates_uniqueness_of :movie, scope: :list
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, :overview, presence: true, uniqueness: true
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @list = List.find(params[:id])
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/views/bookmarks/create.html.erb
<h1>CREATEBOOKMARK</h1>

app/views/bookmarks/destroy.html.erb
<h1>Bookmark#destroy</h1>

app/views/bookmarks/new.html.erb
<h1>NEW BOOKMARK</h1>
<br>
<div class="container">
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie %>
    <%= f.input :comment %>
    <%= f.button :submit, class:"btn btn-primary" %>
    <% end %>

  <%= link_to 'BACK TO THE LIST', list_path(@list) %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/create.html.erb
<h1>CREATE LIST</h1>

app/views/lists/index.html.erb
<h1>ALL LISTS</h1>
<br>
<div class="container">

  <ul class="list-group d-flex justify-content-start">
        <% @lists.each do |list| %>
    <li class="list-group-item">
    <%= link_to list.name, list_path(list) %></li>
        <% end %>
  </ul>
<%= cl_image_tag("mountains.jpg",
      width: 400, height: 300, crop: :fill) %>
  <br>

  <button class="btn btn-success">
  <%= link_to 'CREATE NEW LIST', new_list_path %>
  </button>
</div>

app/views/lists/new.html.erb
<h1>NEW LIST</h1>

<%= simple_form_for [@list] do |f| %>
  <%= f.input :name %>
  <%= f.submit class: "btn btn-warning m-2" %>
<% end %>
<button class="btn btn-dark  m-2"><%= link_to 'ALL LISTS', lists_path %></button>

app/views/lists/show.html.erb
<h1> <%= @list.name %> </h1>

<div class="container">
      <div class="row d-flex justify-content-center my-3">
        <div class="row col-4"><% @list.bookmarks.each do |bookmark| %>
            <%= image_tag(bookmark.movie.poster_url) %>
          <div class="d-flex justify-content-between my-3">
            <%= bookmark.movie.title %>
            <%= link_to 'x',  list_bookmark_path(@list, bookmark), data: { turbo_method: :delete }  %>
          </div>
          <% end %>
          </div>
      </div>

  <div class="d-flex mt-2">
    <button class="btn btn-dark col"><%= link_to 'ALL LISTS', lists_path %></button>
    <button class="btn btn-success"><%= link_to 'CREATE BOOKMARK',  new_list_bookmark_path(@list) %></button>
  </div>
</div>